export {
  addKimiHooksToConfigText,
  buildClaudeHookConfig,
  buildClaudeStyleHookConfig,
  buildCodexHookConfig,
  buildCopilotHookConfig,
  buildDevinHookConfig,
  buildDroidHookConfig,
  buildGrokHookConfig,
  buildKimiHookConfig,
  buildKiroHookConfig,
  buildQwenHookConfig,
  CLAUDE_SETTINGS_PATH,
  CODEX_HOOKS_PATH,
  COPILOT_HOOKS_PATH,
  DEVIN_HOOKS_PATH,
  DROID_HOOKS_PATH,
  GROK_HOOKS_PATH,
  KIMI_CONFIG_PATH,
  KIMI_LEGACY_CONFIG_PATH,
  KIRO_HOOKS_PATH,
  QWEN_HOOKS_PATH,
  type HookCommandOptions,
} from '@emdash/shared/agents/plugins/runtime';
