import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Button } from './ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from './ui/dialog';
import { SlugInput } from './ui/slug-input';
import { Label } from './ui/label';
import { Spinner } from './ui/spinner';
import { Separator } from './ui/separator';
import { MultiProviderDropdown } from './MultiProviderDropdown';
import { TaskAdvancedSettings } from './TaskAdvancedSettings';
import { useIntegrationStatus } from './hooks/useIntegrationStatus';
import { type Provider } from '../types';
import { type ProviderRun } from '../types/chat';
import { providerMeta } from '../providers/meta';
import { isValidProviderId } from '@shared/providers/registry';
import { type LinearIssueSummary } from '../types/linear';
import { type GitHubIssueSummary } from '../types/github';
import { type JiraIssueSummary } from '../types/jira';
import {
  generateFriendlyTaskName,
  normalizeTaskName,
  MAX_TASK_NAME_LENGTH,
} from '../lib/taskNames';

const DEFAULT_PROVIDER: Provider = 'claude';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateTask: (
    name: string,
    initialPrompt?: string,
    providerRuns?: ProviderRun[],
    linkedLinearIssue?: LinearIssueSummary | null,
    linkedGithubIssue?: GitHubIssueSummary | null,
    linkedJiraIssue?: JiraIssueSummary | null,
    autoApprove?: boolean,
    useWorktree?: boolean
  ) => void;
  projectName: string;
  defaultBranch: string;
  existingNames?: string[];
  projectPath?: string;
}

const TaskModal: React.FC<TaskModalProps> = ({
  isOpen,
  onClose,
  onCreateTask,
  projectName,
  defaultBranch,
  existingNames = [],
  projectPath,
}) => {
  // Form state
  const [taskName, setTaskName] = useState('');
  const [providerRuns, setProviderRuns] = useState<ProviderRun[]>([
    { provider: DEFAULT_PROVIDER, runs: 1 },
  ]);
  const [defaultProviderFromSettings, setDefaultProviderFromSettings] =
    useState<Provider>(DEFAULT_PROVIDER);
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);

  // Advanced settings state
  const [initialPrompt, setInitialPrompt] = useState('');
  const [selectedLinearIssue, setSelectedLinearIssue] = useState<LinearIssueSummary | null>(null);
  const [selectedGithubIssue, setSelectedGithubIssue] = useState<GitHubIssueSummary | null>(null);
  const [selectedJiraIssue, setSelectedJiraIssue] = useState<JiraIssueSummary | null>(null);
  const [autoApprove, setAutoApprove] = useState(false);
  const [useWorktree, setUseWorktree] = useState(true);

  // Auto-name tracking
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const userHasTypedRef = useRef(false);
  const autoNameInitializedRef = useRef(false);
  const customNameTrackedRef = useRef(false);

  // Integration connections
  const integrations = useIntegrationStatus(isOpen);

  // Computed values
  const activeProviders = useMemo(() => providerRuns.map((pr) => pr.provider), [providerRuns]);
  const hasAutoApproveSupport = activeProviders.every((id) => !!providerMeta[id]?.autoApproveFlag);
  const hasInitialPromptSupport = activeProviders.every(
    (id) => providerMeta[id]?.initialPromptFlag !== undefined
  );

  const normalizedExisting = useMemo(
    () => existingNames.map((n) => normalizeTaskName(n)).filter(Boolean),
    [existingNames]
  );

  // Validation
  const validate = useCallback(
    (value: string): string | null => {
      const normalized = normalizeTaskName(value);
      if (!normalized) return 'Please enter a Task name.';
      if (normalizedExisting.includes(normalized)) return 'A Task with this name already exists.';
      if (normalized.length > MAX_TASK_NAME_LENGTH)
        return `Task name is too long (max ${MAX_TASK_NAME_LENGTH} characters).`;
      return null;
    },
    [normalizedExisting]
  );

  // Clear issues when provider doesn't support them
  useEffect(() => {
    if (!hasInitialPromptSupport) {
      setSelectedLinearIssue(null);
      setSelectedGithubIssue(null);
      setSelectedJiraIssue(null);
      setInitialPrompt('');
    }
  }, [hasInitialPromptSupport]);

  // Clear auto-approve if not supported
  useEffect(() => {
    if (!hasAutoApproveSupport && autoApprove) setAutoApprove(false);
  }, [hasAutoApproveSupport, autoApprove]);

  // Reset form and load settings when modal opens
  useEffect(() => {
    if (!isOpen) return;

    // Reset state
    setTaskName('');
    setAutoGeneratedName('');
    setError(null);
    setTouched(false);
    setInitialPrompt('');
    setSelectedLinearIssue(null);
    setSelectedGithubIssue(null);
    setSelectedJiraIssue(null);
    setAutoApprove(false);
    setUseWorktree(true);
    userHasTypedRef.current = false;
    autoNameInitializedRef.current = false;
    customNameTrackedRef.current = false;

    // Generate initial name
    const suggested = generateFriendlyTaskName(normalizedExisting);
    setAutoGeneratedName(suggested);
    setTaskName(suggested);
    setError(validate(suggested));
    autoNameInitializedRef.current = true;

    // Load settings
    let cancel = false;
    window.electronAPI.getSettings().then((res) => {
      if (cancel) return;
      const settings = res?.success ? res.settings : undefined;

      const settingsProvider = settings?.defaultProvider;
      const provider: Provider = isValidProviderId(settingsProvider)
        ? (settingsProvider as Provider)
        : DEFAULT_PROVIDER;
      setDefaultProviderFromSettings(provider);
      setProviderRuns([{ provider, runs: 1 }]);

      const autoApproveByDefault = settings?.tasks?.autoApproveByDefault ?? false;
      setAutoApprove(autoApproveByDefault && !!providerMeta[provider]?.autoApproveFlag);

      // Handle auto-generate setting
      if (settings?.tasks?.autoGenerateName === false && !userHasTypedRef.current) {
        setAutoGeneratedName('');
        setTaskName('');
        setError(null);
      }
    });

    return () => {
      cancel = true;
    };
  }, [isOpen]);

  const handleNameChange = (val: string) => {
    setTaskName(val);
    setError(validate(val));
    userHasTypedRef.current = true;

    // Track custom naming for telemetry (only once per session)
    if (
      autoGeneratedName &&
      val !== autoGeneratedName &&
      val.trim() &&
      !customNameTrackedRef.current
    ) {
      customNameTrackedRef.current = true;
      void (async () => {
        const { captureTelemetry } = await import('../lib/telemetryClient');
        captureTelemetry('task_custom_named', { custom_name: 'true' });
      })();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched(true);

    const err = validate(taskName);
    if (err) {
      setError(err);
      return;
    }

    setIsCreating(true);
    try {
      await onCreateTask(
        normalizeTaskName(taskName),
        hasInitialPromptSupport && initialPrompt.trim() ? initialPrompt.trim() : undefined,
        providerRuns,
        selectedLinearIssue,
        selectedGithubIssue,
        selectedJiraIssue,
        hasAutoApproveSupport ? autoApprove : false,
        useWorktree
      );
      onClose();
    } catch (error) {
      console.error('Failed to create task:', error);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && !isCreating && onClose()}>
      <DialogContent className="max-h-[calc(100vh-48px)] max-w-md overflow-y-auto overflow-x-hidden">
        <DialogHeader>
          <DialogTitle>New Task</DialogTitle>
          <DialogDescription className="text-xs">
            {projectName} • from origin/{defaultBranch}
          </DialogDescription>
        </DialogHeader>

        <Separator />

        <form onSubmit={handleSubmit} className="space-y-4 overflow-hidden">
          <div>
            <Label htmlFor="task-name" className="mb-2 block">
              Task name
            </Label>
            <SlugInput
              id="task-name"
              value={taskName}
              onChange={handleNameChange}
              onBlur={() => setTouched(true)}
              placeholder="refactor-api-routes"
              maxLength={MAX_TASK_NAME_LENGTH}
              className={`w-full ${touched && error ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive' : ''}`}
              aria-invalid={touched && !!error}
              autoFocus
            />
            {touched && error && <p className="mt-1 text-xs text-destructive">{error}</p>}
          </div>

          <div className="flex items-center gap-4">
            <Label className="shrink-0">AI Provider</Label>
            <MultiProviderDropdown
              providerRuns={providerRuns}
              onChange={setProviderRuns}
              defaultProvider={defaultProviderFromSettings}
            />
          </div>

          <TaskAdvancedSettings
            isOpen={isOpen}
            projectPath={projectPath}
            useWorktree={useWorktree}
            onUseWorktreeChange={setUseWorktree}
            autoApprove={autoApprove}
            onAutoApproveChange={setAutoApprove}
            hasAutoApproveSupport={hasAutoApproveSupport}
            initialPrompt={initialPrompt}
            onInitialPromptChange={setInitialPrompt}
            hasInitialPromptSupport={hasInitialPromptSupport}
            selectedLinearIssue={selectedLinearIssue}
            onLinearIssueChange={setSelectedLinearIssue}
            isLinearConnected={integrations.isLinearConnected}
            onLinearConnect={integrations.handleLinearConnect}
            selectedGithubIssue={selectedGithubIssue}
            onGithubIssueChange={setSelectedGithubIssue}
            isGithubConnected={integrations.isGithubConnected}
            onGithubConnect={integrations.handleGithubConnect}
            githubLoading={integrations.githubLoading}
            githubInstalled={integrations.githubInstalled}
            selectedJiraIssue={selectedJiraIssue}
            onJiraIssueChange={setSelectedJiraIssue}
            isJiraConnected={integrations.isJiraConnected}
            onJiraConnect={integrations.handleJiraConnect}
          />

          <DialogFooter>
            <Button type="submit" disabled={!!validate(taskName) || isCreating}>
              {isCreating ? (
                <>
                  <Spinner size="sm" className="mr-2" />
                  Creating...
                </>
              ) : (
                'Create'
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default TaskModal;
