import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Button } from './ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from './ui/dialog';
import { SlugInput } from './ui/slug-input';
import { Label } from './ui/label';
import { Spinner } from './ui/spinner';
import { Separator } from './ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { ScrollArea } from './ui/scroll-area';
import { Input } from './ui/input';
import { MultiProviderDropdown } from './MultiProviderDropdown';
import { TaskAdvancedSettings } from './TaskAdvancedSettings';
import { useIntegrationStatus } from './hooks/useIntegrationStatus';
import { type Provider } from '../types';
import { type ProviderRun } from '../types/chat';
import { providerMeta } from '../providers/meta';
import { isValidProviderId } from '@shared/providers/registry';
import { type LinearIssueSummary } from '../types/linear';
import { type GitHubIssueSummary } from '../types/github';
import { type JiraIssueSummary } from '../types/jira';
import {
  generateFriendlyTaskName,
  normalizeTaskName,
  MAX_TASK_NAME_LENGTH,
} from '../lib/taskNames';
import { type RemoteBranchOption } from './BaseBranchControls';

const DEFAULT_PROVIDER: Provider = 'claude';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateTask: (
    name: string,
    initialPrompt?: string,
    providerRuns?: ProviderRun[],
    linkedLinearIssue?: LinearIssueSummary | null,
    linkedGithubIssue?: GitHubIssueSummary | null,
    linkedJiraIssue?: JiraIssueSummary | null,
    autoApprove?: boolean,
    useWorktree?: boolean,
    baseRef?: string
  ) => void;
  projectName: string;
  defaultBranch: string;
  existingNames?: string[];
  projectPath?: string;
  branchOptions?: RemoteBranchOption[];
  isLoadingBranches?: boolean;
}

const TaskModal: React.FC<TaskModalProps> = ({
  isOpen,
  onClose,
  onCreateTask,
  projectName,
  defaultBranch,
  existingNames = [],
  projectPath,
  branchOptions = [],
  isLoadingBranches = false,
}) => {
  // Form state
  const [taskName, setTaskName] = useState('');
  const [providerRuns, setProviderRuns] = useState<ProviderRun[]>([
    { provider: DEFAULT_PROVIDER, runs: 1 },
  ]);
  const [defaultProviderFromSettings, setDefaultProviderFromSettings] =
    useState<Provider>(DEFAULT_PROVIDER);
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);

  // Advanced settings state
  const [initialPrompt, setInitialPrompt] = useState('');
  const [selectedLinearIssue, setSelectedLinearIssue] = useState<LinearIssueSummary | null>(null);
  const [selectedGithubIssue, setSelectedGithubIssue] = useState<GitHubIssueSummary | null>(null);
  const [selectedJiraIssue, setSelectedJiraIssue] = useState<JiraIssueSummary | null>(null);
  const [autoApprove, setAutoApprove] = useState(false);
  const [useWorktree, setUseWorktree] = useState(true);

  // Branch selection state
  const [selectedBranch, setSelectedBranch] = useState(defaultBranch);
  const [branchSearchTerm, setBranchSearchTerm] = useState('');
  const [branchSelectOpen, setBranchSelectOpen] = useState(false);
  const branchSearchInputRef = useRef<HTMLInputElement | null>(null);

  // Auto-name tracking
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const userHasTypedRef = useRef(false);
  const autoNameInitializedRef = useRef(false);
  const customNameTrackedRef = useRef(false);

  // Integration connections
  const integrations = useIntegrationStatus(isOpen);

  // Computed values
  const activeProviders = useMemo(() => providerRuns.map((pr) => pr.provider), [providerRuns]);
  const hasAutoApproveSupport = activeProviders.every((id) => !!providerMeta[id]?.autoApproveFlag);
  const hasInitialPromptSupport = activeProviders.every(
    (id) => providerMeta[id]?.initialPromptFlag !== undefined
  );

  const normalizedExisting = useMemo(
    () => existingNames.map((n) => normalizeTaskName(n)).filter(Boolean),
    [existingNames]
  );

  // Branch selection computed values
  const filteredBranchOptions = useMemo(() => {
    if (!branchSearchTerm.trim()) return branchOptions;
    const query = branchSearchTerm.trim().toLowerCase();
    return branchOptions.filter((option) => option.label.toLowerCase().includes(query));
  }, [branchOptions, branchSearchTerm]);

  const displayedBranchOptions = useMemo(() => {
    if (!selectedBranch) return filteredBranchOptions;
    const hasSelection = filteredBranchOptions.some((option) => option.value === selectedBranch);
    if (hasSelection) return filteredBranchOptions;
    const selectedOption = branchOptions.find((option) => option.value === selectedBranch);
    if (!selectedOption) return filteredBranchOptions;
    return [selectedOption, ...filteredBranchOptions];
  }, [filteredBranchOptions, branchOptions, selectedBranch]);

  const branchNavigationKeys = useMemo(
    () => new Set(['ArrowUp', 'ArrowDown', 'PageUp', 'PageDown', 'Home', 'End', 'Enter', 'Escape']),
    []
  );

  // Focus branch search input when dropdown opens
  useEffect(() => {
    if (branchSelectOpen) {
      requestAnimationFrame(() => branchSearchInputRef.current?.focus());
    } else {
      setBranchSearchTerm('');
    }
  }, [branchSelectOpen]);

  // Validation
  const validate = useCallback(
    (value: string): string | null => {
      const normalized = normalizeTaskName(value);
      if (!normalized) return 'Please enter a Task name.';
      if (normalizedExisting.includes(normalized)) return 'A Task with this name already exists.';
      if (normalized.length > MAX_TASK_NAME_LENGTH)
        return `Task name is too long (max ${MAX_TASK_NAME_LENGTH} characters).`;
      return null;
    },
    [normalizedExisting]
  );

  // Clear issues when provider doesn't support them
  useEffect(() => {
    if (!hasInitialPromptSupport) {
      setSelectedLinearIssue(null);
      setSelectedGithubIssue(null);
      setSelectedJiraIssue(null);
      setInitialPrompt('');
    }
  }, [hasInitialPromptSupport]);

  // Clear auto-approve if not supported
  useEffect(() => {
    if (!hasAutoApproveSupport && autoApprove) setAutoApprove(false);
  }, [hasAutoApproveSupport, autoApprove]);

  // Reset form and load settings when modal opens
  useEffect(() => {
    if (!isOpen) return;

    // Reset state
    setTaskName('');
    setAutoGeneratedName('');
    setError(null);
    setTouched(false);
    setInitialPrompt('');
    setSelectedLinearIssue(null);
    setSelectedGithubIssue(null);
    setSelectedJiraIssue(null);
    setAutoApprove(false);
    setUseWorktree(true);
    setSelectedBranch(defaultBranch);
    setBranchSearchTerm('');
    setBranchSelectOpen(false);
    userHasTypedRef.current = false;
    autoNameInitializedRef.current = false;
    customNameTrackedRef.current = false;

    // Generate initial name
    const suggested = generateFriendlyTaskName(normalizedExisting);
    setAutoGeneratedName(suggested);
    setTaskName(suggested);
    setError(validate(suggested));
    autoNameInitializedRef.current = true;

    // Load settings
    let cancel = false;
    window.electronAPI.getSettings().then((res) => {
      if (cancel) return;
      const settings = res?.success ? res.settings : undefined;

      const settingsProvider = settings?.defaultProvider;
      const provider: Provider = isValidProviderId(settingsProvider)
        ? (settingsProvider as Provider)
        : DEFAULT_PROVIDER;
      setDefaultProviderFromSettings(provider);
      setProviderRuns([{ provider, runs: 1 }]);

      const autoApproveByDefault = settings?.tasks?.autoApproveByDefault ?? false;
      setAutoApprove(autoApproveByDefault && !!providerMeta[provider]?.autoApproveFlag);

      // Handle auto-generate setting
      if (settings?.tasks?.autoGenerateName === false && !userHasTypedRef.current) {
        setAutoGeneratedName('');
        setTaskName('');
        setError(null);
      }
    });

    return () => {
      cancel = true;
    };
  }, [isOpen]);

  const handleNameChange = (val: string) => {
    setTaskName(val);
    setError(validate(val));
    userHasTypedRef.current = true;

    // Track custom naming for telemetry (only once per session)
    if (
      autoGeneratedName &&
      val !== autoGeneratedName &&
      val.trim() &&
      !customNameTrackedRef.current
    ) {
      customNameTrackedRef.current = true;
      void (async () => {
        const { captureTelemetry } = await import('../lib/telemetryClient');
        captureTelemetry('task_custom_named', { custom_name: 'true' });
      })();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched(true);

    const err = validate(taskName);
    if (err) {
      setError(err);
      return;
    }

    setIsCreating(true);
    try {
      await onCreateTask(
        normalizeTaskName(taskName),
        hasInitialPromptSupport && initialPrompt.trim() ? initialPrompt.trim() : undefined,
        providerRuns,
        selectedLinearIssue,
        selectedGithubIssue,
        selectedJiraIssue,
        hasAutoApproveSupport ? autoApprove : false,
        useWorktree,
        selectedBranch
      );
      onClose();
    } catch (error) {
      console.error('Failed to create task:', error);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && !isCreating && onClose()}>
      <DialogContent className="max-h-[calc(100vh-48px)] max-w-md overflow-visible">
        <DialogHeader>
          <DialogTitle>New Task</DialogTitle>
          <div className="space-y-1 pt-1">
            <p className="text-sm font-medium text-foreground">{projectName}</p>
            <div className="flex items-center gap-1.5">
              <span className="text-xs text-muted-foreground">from</span>
              {branchOptions.length > 0 ? (
                <Select
                  value={selectedBranch}
                  onValueChange={setSelectedBranch}
                  disabled={isLoadingBranches}
                  open={branchSelectOpen}
                  onOpenChange={setBranchSelectOpen}
                >
                  <SelectTrigger className="h-auto border-none bg-transparent p-0 text-xs text-muted-foreground shadow-none hover:text-foreground focus:ring-0 [&>svg]:ml-0.5 [&>svg]:h-3 [&>svg]:w-3">
                    <SelectValue placeholder={isLoadingBranches ? 'Loading...' : selectedBranch} />
                  </SelectTrigger>
                  <SelectContent
                    className="[&>[data-radix-select-scroll-down-button]]:hidden [&>[data-radix-select-scroll-up-button]]:hidden"
                    style={{ minWidth: '200px' }}
                  >
                    <div className="px-2 pb-2 pt-2" onPointerDown={(event) => event.stopPropagation()}>
                      <Input
                        ref={branchSearchInputRef}
                        value={branchSearchTerm}
                        onChange={(event) => setBranchSearchTerm(event.currentTarget.value)}
                        onKeyDown={(event) => {
                          if (!branchNavigationKeys.has(event.key)) {
                            event.stopPropagation();
                          }
                        }}
                        placeholder="Search branches"
                        className="h-7 bg-popover px-2 py-1 text-xs"
                      />
                    </div>
                    <ScrollArea
                      className="w-full"
                      style={{
                        height: `${Math.min(256, Math.max(displayedBranchOptions.length, 1) * 32)}px`,
                        maxHeight: '256px',
                      }}
                    >
                      <div className="space-y-0 pr-3">
                        {displayedBranchOptions.length > 0 ? (
                          displayedBranchOptions.map((option) => (
                            <SelectItem key={option.value} value={option.value}>
                              {option.label}
                            </SelectItem>
                          ))
                        ) : (
                          <div className="px-3 py-2 text-xs text-muted-foreground">
                            No matching branches
                          </div>
                        )}
                      </div>
                    </ScrollArea>
                  </SelectContent>
                </Select>
              ) : (
                <span className="text-xs text-muted-foreground">{selectedBranch}</span>
              )}
            </div>
          </div>
        </DialogHeader>

        <Separator />

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="task-name" className="mb-2 block">
              Task name
            </Label>
            <SlugInput
              id="task-name"
              value={taskName}
              onChange={handleNameChange}
              onBlur={() => setTouched(true)}
              placeholder="refactor-api-routes"
              maxLength={MAX_TASK_NAME_LENGTH}
              className={`w-full ${touched && error ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive' : ''}`}
              aria-invalid={touched && !!error}
              autoFocus
            />
            {touched && error && <p className="mt-1 text-xs text-destructive">{error}</p>}
          </div>

          <div className="flex items-center gap-4">
            <Label className="shrink-0">AI Provider</Label>
            <MultiProviderDropdown
              providerRuns={providerRuns}
              onChange={setProviderRuns}
              defaultProvider={defaultProviderFromSettings}
            />
          </div>

          <TaskAdvancedSettings
            isOpen={isOpen}
            projectPath={projectPath}
            useWorktree={useWorktree}
            onUseWorktreeChange={setUseWorktree}
            autoApprove={autoApprove}
            onAutoApproveChange={setAutoApprove}
            hasAutoApproveSupport={hasAutoApproveSupport}
            initialPrompt={initialPrompt}
            onInitialPromptChange={setInitialPrompt}
            hasInitialPromptSupport={hasInitialPromptSupport}
            selectedLinearIssue={selectedLinearIssue}
            onLinearIssueChange={setSelectedLinearIssue}
            isLinearConnected={integrations.isLinearConnected}
            onLinearConnect={integrations.handleLinearConnect}
            selectedGithubIssue={selectedGithubIssue}
            onGithubIssueChange={setSelectedGithubIssue}
            isGithubConnected={integrations.isGithubConnected}
            onGithubConnect={integrations.handleGithubConnect}
            githubLoading={integrations.githubLoading}
            githubInstalled={integrations.githubInstalled}
            selectedJiraIssue={selectedJiraIssue}
            onJiraIssueChange={setSelectedJiraIssue}
            isJiraConnected={integrations.isJiraConnected}
            onJiraConnect={integrations.handleJiraConnect}
          />

          <DialogFooter>
            <Button type="submit" disabled={!!validate(taskName) || isCreating}>
              {isCreating ? (
                <>
                  <Spinner size="sm" className="mr-2" />
                  Creating...
                </>
              ) : (
                'Create'
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default TaskModal;
