// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Shape-compatible with Terrazzo output for backward compat with metrics.ts.
export const tokens = {
  'color.neutral.1': {
    '.': { colorSpace: 'display-p3', channels: [0.9884, 0.988, 0.9881], alpha: 1 },
  },
  'color.neutral.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9437, 0.9432, 0.9433], alpha: 1 },
  },
  'color.neutral.3': {
    '.': { colorSpace: 'display-p3', channels: [0.8995, 0.8987, 0.8989], alpha: 1 },
  },
  'color.neutral.4': {
    '.': { colorSpace: 'display-p3', channels: [0.8559, 0.8545, 0.8549], alpha: 1 },
  },
  'color.neutral.5': {
    '.': { colorSpace: 'display-p3', channels: [0.8128, 0.8107, 0.8113], alpha: 1 },
  },
  'color.neutral.6': {
    '.': { colorSpace: 'display-p3', channels: [0.7703, 0.7673, 0.7681], alpha: 1 },
  },
  'color.neutral.7': {
    '.': { colorSpace: 'display-p3', channels: [0.8109, 0.8067, 0.8078], alpha: 1 },
  },
  'color.neutral.8': {
    '.': { colorSpace: 'display-p3', channels: [0.733, 0.728, 0.7294], alpha: 1 },
  },
  'color.neutral.9': {
    '.': { colorSpace: 'display-p3', channels: [0.5582, 0.5525, 0.554], alpha: 1 },
  },
  'color.neutral.10': {
    '.': { colorSpace: 'display-p3', channels: [0.5168, 0.5113, 0.5128], alpha: 1 },
  },
  'color.neutral.11': {
    '.': { colorSpace: 'display-p3', channels: [0.3826, 0.3787, 0.3798], alpha: 1 },
  },
  'color.neutral.12': {
    '.': { colorSpace: 'display-p3', channels: [0.1329, 0.1309, 0.1314], alpha: 1 },
  },
  'color.accent.1': {
    '.': { colorSpace: 'display-p3', channels: [0.9707, 0.9965, 0.9854], alpha: 1 },
  },
  'color.accent.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9155, 0.9565, 0.939], alpha: 1 },
  },
  'color.accent.3': {
    '.': { colorSpace: 'display-p3', channels: [0.85, 0.9216, 0.8914], alpha: 1 },
  },
  'color.accent.4': {
    '.': { colorSpace: 'display-p3', channels: [0.7772, 0.8897, 0.8431], alpha: 1 },
  },
  'color.accent.5': {
    '.': { colorSpace: 'display-p3', channels: [0.6884, 0.8635, 0.7932], alpha: 1 },
  },
  'color.accent.6': {
    '.': { colorSpace: 'display-p3', channels: [0.5791, 0.8421, 0.7417], alpha: 1 },
  },
  'color.accent.7': {
    '.': { colorSpace: 'display-p3', channels: [0.5072, 0.8816, 0.7469], alpha: 1 },
  },
  'color.accent.8': {
    '.': { colorSpace: 'display-p3', channels: [0.3284, 0.8081, 0.6525], alpha: 1 },
  },
  'color.accent.9': { '.': { colorSpace: 'display-p3', channels: [0, 0.6298, 0.4648], alpha: 1 } },
  'color.accent.10': { '.': { colorSpace: 'display-p3', channels: [0, 0.5868, 0.4314], alpha: 1 } },
  'color.accent.11': { '.': { colorSpace: 'display-p3', channels: [0, 0.4372, 0.3201], alpha: 1 } },
  'color.accent.12': { '.': { colorSpace: 'display-p3', channels: [0, 0.1411, 0.0863], alpha: 1 } },
  'color.green.1': {
    '.': { colorSpace: 'display-p3', channels: [0.9768, 0.9954, 0.9754], alpha: 1 },
  },
  'color.green.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9253, 0.9548, 0.9232], alpha: 1 },
  },
  'color.green.3': {
    '.': { colorSpace: 'display-p3', channels: [0.8675, 0.9185, 0.8638], alpha: 1 },
  },
  'color.green.4': {
    '.': { colorSpace: 'display-p3', channels: [0.8054, 0.885, 0.7999], alpha: 1 },
  },
  'color.green.5': {
    '.': { colorSpace: 'display-p3', channels: [0.7341, 0.8564, 0.7264], alpha: 1 },
  },
  'color.green.6': {
    '.': { colorSpace: 'display-p3', channels: [0.6525, 0.8318, 0.6428], alpha: 1 },
  },
  'color.green.7': {
    '.': { colorSpace: 'display-p3', channels: [0.6251, 0.8728, 0.6141], alpha: 1 },
  },
  'color.green.8': {
    '.': { colorSpace: 'display-p3', channels: [0.5038, 0.8021, 0.4947], alpha: 1 },
  },
  'color.green.9': {
    '.': { colorSpace: 'display-p3', channels: [0.2542, 0.6265, 0.2594], alpha: 1 },
  },
  'color.green.10': {
    '.': { colorSpace: 'display-p3', channels: [0.2304, 0.5845, 0.236], alpha: 1 },
  },
  'color.green.11': {
    '.': { colorSpace: 'display-p3', channels: [0.1881, 0.4341, 0.1888], alpha: 1 },
  },
  'color.green.12': {
    '.': { colorSpace: 'display-p3', channels: [0.0044, 0.1373, 0.0106], alpha: 1 },
  },
  'color.red.1': { '.': { colorSpace: 'display-p3', channels: [1, 0.9804, 0.9772], alpha: 1 } },
  'color.red.2': { '.': { colorSpace: 'display-p3', channels: [0.9756, 0.931, 0.926], alpha: 1 } },
  'color.red.3': {
    '.': { colorSpace: 'display-p3', channels: [0.9541, 0.8772, 0.8687], alpha: 1 },
  },
  'color.red.4': {
    '.': { colorSpace: 'display-p3', channels: [0.9395, 0.8204, 0.8078], alpha: 1 },
  },
  'color.red.5': {
    '.': { colorSpace: 'display-p3', channels: [0.9377, 0.7569, 0.7389], alpha: 1 },
  },
  'color.red.6': { '.': { colorSpace: 'display-p3', channels: [0.9467, 0.685, 0.6619], alpha: 1 } },
  'color.red.7': { '.': { colorSpace: 'display-p3', channels: [1, 0.7165, 0.6895], alpha: 1 } },
  'color.red.8': { '.': { colorSpace: 'display-p3', channels: [1, 0.5988, 0.5722], alpha: 1 } },
  'color.red.9': {
    '.': { colorSpace: 'display-p3', channels: [0.8746, 0.3651, 0.3565], alpha: 1 },
  },
  'color.red.10': {
    '.': { colorSpace: 'display-p3', channels: [0.8216, 0.3379, 0.3303], alpha: 1 },
  },
  'color.red.11': {
    '.': { colorSpace: 'display-p3', channels: [0.5963, 0.2559, 0.2471], alpha: 1 },
  },
  'color.red.12': {
    '.': { colorSpace: 'display-p3', channels: [0.2034, 0.0184, 0.0276], alpha: 1 },
  },
  'color.amber.1': {
    '.': { colorSpace: 'display-p3', channels: [0.9993, 0.9871, 0.963], alpha: 1 },
  },
  'color.amber.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9611, 0.9416, 0.9034], alpha: 1 },
  },
  'color.amber.3': {
    '.': { colorSpace: 'display-p3', channels: [0.9296, 0.8956, 0.8292], alpha: 1 },
  },
  'color.amber.4': {
    '.': { colorSpace: 'display-p3', channels: [0.9024, 0.8491, 0.7454], alpha: 1 },
  },
  'color.amber.5': {
    '.': { colorSpace: 'display-p3', channels: [0.8835, 0.801, 0.6407], alpha: 1 },
  },
  'color.amber.6': {
    '.': { colorSpace: 'display-p3', channels: [0.8723, 0.7501, 0.5113], alpha: 1 },
  },
  'color.amber.7': {
    '.': { colorSpace: 'display-p3', channels: [0.9497, 0.7795, 0.4395], alpha: 1 },
  },
  'color.amber.8': {
    '.': { colorSpace: 'display-p3', channels: [0.8955, 0.6904, 0.2483], alpha: 1 },
  },
  'color.amber.9': { '.': { colorSpace: 'display-p3', channels: [0.7717, 0.5443, 0], alpha: 1 } },
  'color.amber.10': { '.': { colorSpace: 'display-p3', channels: [0.6988, 0.49, 0], alpha: 1 } },
  'color.amber.11': { '.': { colorSpace: 'display-p3', channels: [0.4753, 0.3235, 0], alpha: 1 } },
  'color.amber.12': { '.': { colorSpace: 'display-p3', channels: [0.1545, 0.0858, 0], alpha: 1 } },
  'color.blue.1': { '.': { colorSpace: 'display-p3', channels: [0.9743, 0.9904, 1], alpha: 1 } },
  'color.blue.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9213, 0.9468, 0.9816], alpha: 1 },
  },
  'color.blue.3': {
    '.': { colorSpace: 'display-p3', channels: [0.8604, 0.9046, 0.965], alpha: 1 },
  },
  'color.blue.4': {
    '.': { colorSpace: 'display-p3', channels: [0.7944, 0.8631, 0.9573], alpha: 1 },
  },
  'color.blue.5': {
    '.': { colorSpace: 'display-p3', channels: [0.7173, 0.8222, 0.9668], alpha: 1 },
  },
  'color.blue.6': {
    '.': { colorSpace: 'display-p3', channels: [0.6279, 0.7807, 0.9926], alpha: 1 },
  },
  'color.blue.7': { '.': { colorSpace: 'display-p3', channels: [0.6473, 0.8163, 1], alpha: 1 } },
  'color.blue.8': { '.': { colorSpace: 'display-p3', channels: [0.5093, 0.7354, 1], alpha: 1 } },
  'color.blue.9': {
    '.': { colorSpace: 'display-p3', channels: [0.2318, 0.5438, 0.9627], alpha: 1 },
  },
  'color.blue.10': {
    '.': { colorSpace: 'display-p3', channels: [0.205, 0.5022, 0.8993], alpha: 1 },
  },
  'color.blue.11': {
    '.': { colorSpace: 'display-p3', channels: [0.1721, 0.3782, 0.6587], alpha: 1 },
  },
  'color.blue.12': { '.': { colorSpace: 'display-p3', channels: [0, 0.0948, 0.2443], alpha: 1 } },
  'color.orange.1': { '.': { colorSpace: 'display-p3', channels: [1, 0.9835, 0.9668], alpha: 1 } },
  'color.orange.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9711, 0.9359, 0.9094], alpha: 1 },
  },
  'color.orange.3': {
    '.': { colorSpace: 'display-p3', channels: [0.9466, 0.8857, 0.8398], alpha: 1 },
  },
  'color.orange.4': {
    '.': { colorSpace: 'display-p3', channels: [0.9282, 0.8336, 0.7622], alpha: 1 },
  },
  'color.orange.5': {
    '.': { colorSpace: 'display-p3', channels: [0.9215, 0.7769, 0.6675], alpha: 1 },
  },
  'color.orange.6': {
    '.': { colorSpace: 'display-p3', channels: [0.9249, 0.7144, 0.5538], alpha: 1 },
  },
  'color.orange.7': { '.': { colorSpace: 'display-p3', channels: [1, 0.7393, 0.5147], alpha: 1 } },
  'color.orange.8': {
    '.': { colorSpace: 'display-p3', channels: [0.9847, 0.6386, 0.3613], alpha: 1 },
  },
  'color.orange.9': { '.': { colorSpace: 'display-p3', channels: [0.8425, 0.4296, 0], alpha: 1 } },
  'color.orange.10': { '.': { colorSpace: 'display-p3', channels: [0.781, 0.3897, 0], alpha: 1 } },
  'color.orange.11': {
    '.': { colorSpace: 'display-p3', channels: [0.5743, 0.2981, 0.0031], alpha: 1 },
  },
  'color.orange.12': { '.': { colorSpace: 'display-p3', channels: [0.1897, 0.0496, 0], alpha: 1 } },
  'color.purple.1': { '.': { colorSpace: 'display-p3', channels: [0.9921, 0.9829, 1], alpha: 1 } },
  'color.purple.2': {
    '.': { colorSpace: 'display-p3', channels: [0.9496, 0.935, 0.9747], alpha: 1 },
  },
  'color.purple.3': {
    '.': { colorSpace: 'display-p3', channels: [0.9099, 0.8843, 0.9531], alpha: 1 },
  },
  'color.purple.4': {
    '.': { colorSpace: 'display-p3', channels: [0.872, 0.8316, 0.9389], alpha: 1 },
  },
  'color.purple.5': {
    '.': { colorSpace: 'display-p3', channels: [0.8376, 0.7744, 0.9388], alpha: 1 },
  },
  'color.purple.6': {
    '.': { colorSpace: 'display-p3', channels: [0.8067, 0.7115, 0.9521], alpha: 1 },
  },
  'color.purple.7': { '.': { colorSpace: 'display-p3', channels: [0.8672, 0.7434, 1], alpha: 1 } },
  'color.purple.8': { '.': { colorSpace: 'display-p3', channels: [0.8079, 0.6411, 1], alpha: 1 } },
  'color.purple.9': {
    '.': { colorSpace: 'display-p3', channels: [0.6529, 0.4392, 0.9177], alpha: 1 },
  },
  'color.purple.10': {
    '.': { colorSpace: 'display-p3', channels: [0.6027, 0.3993, 0.8529], alpha: 1 },
  },
  'color.purple.11': {
    '.': { colorSpace: 'display-p3', channels: [0.4479, 0.3067, 0.6268], alpha: 1 },
  },
  'color.purple.12': {
    '.': { colorSpace: 'display-p3', channels: [0.1584, 0.0777, 0.2509], alpha: 1 },
  },
  'type.body': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.body-bold': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 600,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.body-italic': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
      fontStyle: 'italic',
    },
  },
  'type.body-link': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.h1': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 20, unit: 'px' },
      fontWeight: 600,
      lineHeight: { value: 28, unit: 'px' },
    },
  },
  'type.h2': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 17, unit: 'px' },
      fontWeight: 600,
      lineHeight: { value: 25, unit: 'px' },
    },
  },
  'type.h3': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 600,
      lineHeight: { value: 22, unit: 'px' },
    },
  },
  'type.inline-code': {
    '.': {
      fontFamily: ['JetBrains Mono Variable', 'JetBrains Mono', 'Menlo', 'Monaco', 'monospace'],
      fontSize: { value: 12, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.mention': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.code': {
    '.': {
      fontFamily: ['JetBrains Mono Variable', 'JetBrains Mono', 'Menlo', 'Monaco', 'monospace'],
      fontSize: { value: 13, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
  'type.code-lang': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: { value: 14, unit: 'px' },
      fontWeight: 400,
      lineHeight: { value: 20, unit: 'px' },
    },
  },
};
