// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Shape-compatible with Terrazzo output.

type ColorChannel = { colorSpace: string; channels: number[]; alpha: number };
type CompositeRole = {
  fontFamily: string[];
  fontSize: { value: number; unit: string };
  fontWeight: number;
  lineHeight: { value: number; unit: string };
  fontStyle?: string;
};

export declare const tokens: {
  [key: string]: { '.': ColorChannel | CompositeRole };
};
