// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Source of truth: packages/ui/src/theme/contract/semantic-template.ts

/** Union of all semantic CSS custom property names. */
export type SemanticVar =
  | '--background'
  | '--background-1'
  | '--background-2'
  | '--background-3'
  | '--foreground'
  | '--foreground-inverse'
  | '--foreground-body'
  | '--foreground-muted'
  | '--foreground-passive'
  | '--background-secondary'
  | '--background-secondary-1'
  | '--background-secondary-2'
  | '--background-secondary-3'
  | '--foreground-secondary'
  | '--foreground-secondary-muted'
  | '--foreground-secondary-passive'
  | '--background-tertiary'
  | '--background-tertiary-1'
  | '--background-tertiary-2'
  | '--background-tertiary-3'
  | '--foreground-tertiary'
  | '--foreground-tertiary-muted'
  | '--foreground-tertiary-passive'
  | '--background-quaternary'
  | '--background-quaternary-1'
  | '--background-quaternary-2'
  | '--background-neutral'
  | '--foreground-neutral'
  | '--primary-button-background'
  | '--primary-button-background-hover'
  | '--primary-button-foreground'
  | '--primary-button-border'
  | '--background-destructive'
  | '--background-destructive-1'
  | '--foreground-destructive'
  | '--foreground-destructive-muted'
  | '--border'
  | '--border-1'
  | '--border-2'
  | '--border-destructive'
  | '--border-primary'
  | '--selection'
  | '--selection-foreground'
  | '--status-in-progress'
  | '--status-in-review'
  | '--status-done'
  | '--status-todo'
  | '--status-cancelled'
  | '--foreground-diff-added'
  | '--foreground-diff-modified'
  | '--foreground-diff-deleted'
  | '--foreground-success'
  | '--background-success'
  | '--background-success-hover'
  | '--border-success'
  | '--foreground-error'
  | '--background-error'
  | '--background-error-hover'
  | '--border-error'
  | '--foreground-warning'
  | '--background-warning'
  | '--background-warning-hover'
  | '--border-warning'
  | '--foreground-info'
  | '--background-info'
  | '--background-info-hover'
  | '--border-info'
  | '--foreground-conflict'
  | '--foreground-merged';

/** Array of all semantic CSS custom property names for runtime validation. */
export const SEMANTIC_VARS: readonly SemanticVar[] = [
  '--background',
  '--background-1',
  '--background-2',
  '--background-3',
  '--foreground',
  '--foreground-inverse',
  '--foreground-body',
  '--foreground-muted',
  '--foreground-passive',
  '--background-secondary',
  '--background-secondary-1',
  '--background-secondary-2',
  '--background-secondary-3',
  '--foreground-secondary',
  '--foreground-secondary-muted',
  '--foreground-secondary-passive',
  '--background-tertiary',
  '--background-tertiary-1',
  '--background-tertiary-2',
  '--background-tertiary-3',
  '--foreground-tertiary',
  '--foreground-tertiary-muted',
  '--foreground-tertiary-passive',
  '--background-quaternary',
  '--background-quaternary-1',
  '--background-quaternary-2',
  '--background-neutral',
  '--foreground-neutral',
  '--primary-button-background',
  '--primary-button-background-hover',
  '--primary-button-foreground',
  '--primary-button-border',
  '--background-destructive',
  '--background-destructive-1',
  '--foreground-destructive',
  '--foreground-destructive-muted',
  '--border',
  '--border-1',
  '--border-2',
  '--border-destructive',
  '--border-primary',
  '--selection',
  '--selection-foreground',
  '--status-in-progress',
  '--status-in-review',
  '--status-done',
  '--status-todo',
  '--status-cancelled',
  '--foreground-diff-added',
  '--foreground-diff-modified',
  '--foreground-diff-deleted',
  '--foreground-success',
  '--background-success',
  '--background-success-hover',
  '--border-success',
  '--foreground-error',
  '--background-error',
  '--background-error-hover',
  '--border-error',
  '--foreground-warning',
  '--background-warning',
  '--background-warning-hover',
  '--border-warning',
  '--foreground-info',
  '--background-info',
  '--background-info-hover',
  '--border-info',
  '--foreground-conflict',
  '--foreground-merged',
] as const;
