import { z } from 'zod';
import { transcriptToolCallItemSchema } from './turns/tool-calls';

export const acpPermissionOptionSchema = z.object({
  optionId: z.string(),
  /** Human-readable label from the ACP PermissionOption.name field. */
  name: z.string(),
  /**
   * ACP-defined kind hint. Standard values: 'allow_once', 'allow_always',
   * 'reject_once', 'reject_always'. May be extended by the agent.
   */
  kind: z.union([
    z.literal('allow_once'),
    z.literal('allow_always'),
    z.literal('reject_once'),
    z.literal('reject_always'),
    z.string(),
  ]),
});
export type AcpPermissionOption = z.infer<typeof acpPermissionOptionSchema>;

export const acpPermissionRequestSchema = z.object({
  /** Stable identifier generated by AcpSessionRuntime for this request. */
  requestId: z.string(),
  /** Snapshot of the typed tool call that triggered the request, when ACP provides one. */
  toolCall: transcriptToolCallItemSchema.optional(),
  options: z.array(acpPermissionOptionSchema),
});
export type AcpPermissionRequest = z.infer<typeof acpPermissionRequestSchema>;

export const permissionDecisionSchema = z.object({
  requestId: z.string(),
  optionId: z.string().nullable(),
});
export type PermissionDecision = z.infer<typeof permissionDecisionSchema>;
