import { z } from 'zod';

export const acpPermissionOptionSchema = z.object({
  optionId: z.string(),
  /** Human-readable label from the ACP PermissionOption.name field. */
  name: z.string(),
  /**
   * ACP-defined kind hint. Standard values: 'allow_once', 'allow_always',
   * 'reject_once', 'reject_always'. May be extended by the agent.
   */
  kind: z.union([
    z.literal('allow_once'),
    z.literal('allow_always'),
    z.literal('reject_once'),
    z.literal('reject_always'),
    z.string(),
  ]),
});
export type AcpPermissionOption = z.infer<typeof acpPermissionOptionSchema>;

export const acpPermissionRequestSchema = z.object({
  /** Stable identifier generated by AcpSessionRuntime for this request. */
  requestId: z.string(),
  /** The ACP tool call id that triggered this request (for context). */
  toolCallId: z.string().optional(),
  /** Pre-formatted action title from toolCall.title, e.g. "Read a File". */
  title: z.string(),
  /** ACP tool kind (execute / edit / read / ...) for context. */
  toolKind: z.string().optional(),
  options: z.array(acpPermissionOptionSchema),
});
export type AcpPermissionRequest = z.infer<typeof acpPermissionRequestSchema>;

export const permissionDecisionSchema = z.object({
  requestId: z.string(),
  optionId: z.string().nullable(),
});
export type PermissionDecision = z.infer<typeof permissionDecisionSchema>;
