import type { AcpTerminalExit } from '../transport';

/**
 * Serializable snapshot of a managed terminal's state.
 * Returned by IAcpSessionRuntime.getTerminals() so that a renderer reload
 * can hydrate the full terminal list from the main-process authority without
 * replaying any event stream.
 */
export interface TerminalSnapshot {
  /** Stable id generated by the runtime for this terminal. */
  terminalId: string;
  /** The command that was executed. */
  command: string;
  /** Arguments passed to the command. */
  args: string[];
  /** Working directory the command ran in. */
  cwd: string;
  /**
   * All output captured so far (stdout + stderr merged), encoded as UTF-8.
   * Respects the outputByteLimit ring-buffer; older bytes are discarded first.
   */
  output: string;
  /** True when output was truncated due to the outputByteLimit cap. */
  truncated: boolean;
  /** Non-null once the command has exited. */
  exitStatus: AcpTerminalExit | null;
}
