/**
 * Shared types for ACP permission requests surfaced in the chat composer.
 *
 * These are serializable so they can be persisted in main-process memory,
 * included in SessionState, and transferred to the renderer via IPC events.
 */

export type AcpPermissionOption = {
  optionId: string;
  /** Human-readable label from the ACP PermissionOption.name field. */
  name: string;
  /**
   * ACP-defined kind hint. Standard values: 'allow_once', 'allow_always',
   * 'reject_once', 'reject_always'. May be extended by the agent.
   */
  kind: 'allow_once' | 'allow_always' | 'reject_once' | 'reject_always' | string;
};

export type AcpPermissionRequest = {
  conversationId: string;
  /** Stable identifier generated by AcpSessionManager for this request. */
  requestId: string;
  /** The ACP tool call id that triggered this request (for context). */
  toolCallId?: string;
  /** Pre-formatted action title from toolCall.title, e.g. "Read a File". */
  title: string;
  /** ACP tool kind (execute / edit / read / ...) for context. */
  toolKind?: string;
  options: AcpPermissionOption[];
};
