#!/usr/bin/env tsx
/**
 * build.ts — Theme generation orchestrator.
 *
 * Imports all theme definitions, resolves them into CSS + JS + type artifacts,
 * and writes the output files. Replaces the Terrazzo build step.
 *
 * Emits:
 *   theme.css        — :root palette vars + per-theme (.em<id>) semantic vars + surface vars
 *   semantic.css     — per-theme semantic vars (imported separately by consumers)
 *   tokens.js        — JavaScript token map (shape-compatible with existing metrics.ts usage)
 *   tokens.d.ts      — TypeScript declarations for tokens.js
 *   contract.generated.ts — SemanticVar union type for compile-time safety
 *   themes/<id>.shiki.json — Shiki theme JSON per theme
 *   theme-manifest.ts — list of available themes for the UI picker
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ResolvedTheme } from './define-theme.js';
import { lightTheme } from './themes/light.theme.js';
import { darkTheme } from './themes/dark.theme.js';
import { SEMANTIC_TEMPLATE } from './contract/semantic-template.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const THEMES_DIR = join(__dirname, 'themes');
const THEME_DIR = __dirname;

const ALL_THEMES: ResolvedTheme[] = [lightTheme, darkTheme];

// ── CSS emission ──────────────────────────────────────────────────────────────

/**
 * Emit the full theme.css:
 *   :root { --neutral-1..12 for ALL scales (light theme as defaults) }
 *   .em<id> { all vars for that theme }
 */
function emitThemeCss(themes: ResolvedTheme[]): string {
  const lines: string[] = [
    '/* -------------------------------------------',
    ' *  Generated by packages/ui/src/theme/build.ts',
    ' *  DO NOT EDIT — run pnpm theme:build to regenerate.',
    ' * ------------------------------------------- */',
    '',
  ];

  // :root — default vars using the light theme as fallback
  const defaultTheme = themes.find((t) => t.polarity === 'light') ?? themes[0];
  lines.push(':root {');
  for (const [prop, value] of Object.entries(defaultTheme.cssVars)) {
    lines.push(`  ${prop}: ${value};`);
  }
  lines.push('}', '');

  // Per-theme selectors
  for (const theme of themes) {
    lines.push(`${theme.selector} {`);
    for (const [prop, value] of Object.entries(theme.cssVars)) {
      lines.push(`  ${prop}: ${value};`);
    }
    lines.push('}', '');
  }

  return lines.join('\n');
}

/**
 * Emit semantic.css — only the semantic slot vars, one block per theme.
 * Consumed by consumers who import theme.css + semantic.css separately.
 */
function emitSemanticCss(themes: ResolvedTheme[]): string {
  const semanticSlots = Object.keys(SEMANTIC_TEMPLATE).map((k) => `--${k}`);
  const lines: string[] = [
    '/* Semantic color token aliases per theme.',
    ' * Import after theme.css. Generated by packages/ui/src/theme/build.ts */',
    '',
    '@layer base {',
  ];

  for (const theme of themes) {
    lines.push(`  ${theme.selector} {`);
    for (const slot of semanticSlots) {
      const value = theme.cssVars[slot];
      if (value != null) lines.push(`    ${slot}: ${value};`);
    }
    lines.push('  }', '');
  }

  lines.push('}');
  return lines.join('\n');
}

// ── tokens.js + tokens.d.ts ───────────────────────────────────────────────────

/**
 * Build the tokens.js export map — shape-compatible with the Terrazzo output
 * consumed by chat-ui/src/core/metrics.ts.
 *
 * The existing metrics.ts accesses tokens['type.body']['.'].fontFamily etc.,
 * so we preserve the flat dot-path key format from the original Terrazzo output.
 *
 * Color tokens are sourced from the generated theme's scales.
 * Typography tokens are static design values.
 */
function emitTokensJs(theme: ResolvedTheme): string {
  const colorEntries: string[] = [];

  // Color tokens: 'color.neutral.1': { '.': { colorSpace, channels, alpha } }
  for (const [scaleName, ramp] of Object.entries(theme.scales)) {
    ramp.steps.forEach((color: string, i: number) => {
      // Parse the p3 color string back to channels for Terrazzo-compat shape
      const match = color.match(/color\(display-p3 ([\d.]+) ([\d.]+) ([\d.]+)\)/);
      const channels = match
        ? [parseFloat(match[1]), parseFloat(match[2]), parseFloat(match[3])]
        : [0, 0, 0];
      colorEntries.push(
        `  'color.${scaleName}.${i + 1}': { '.': { colorSpace: 'display-p3', channels: [${channels.join(', ')}], alpha: 1 } }`,
      );
    });
  }

  // Typography composite tokens in Terrazzo shape (type.* with '.' sub-key)
  const SANS = "['Inter Variable', 'sans-serif']";
  const MONO = "['JetBrains Mono Variable', 'JetBrains Mono', 'Menlo', 'Monaco', 'monospace']";

  const typeEntries = [
    `  'type.body': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.body-bold': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 600, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.body-italic': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' }, fontStyle: 'italic' } }`,
    `  'type.body-link': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.h1': { '.': { fontFamily: ${SANS}, fontSize: { value: 20, unit: 'px' }, fontWeight: 600, lineHeight: { value: 28, unit: 'px' } } }`,
    `  'type.h2': { '.': { fontFamily: ${SANS}, fontSize: { value: 17, unit: 'px' }, fontWeight: 600, lineHeight: { value: 25, unit: 'px' } } }`,
    `  'type.h3': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 600, lineHeight: { value: 22, unit: 'px' } } }`,
    `  'type.inline-code': { '.': { fontFamily: ${MONO}, fontSize: { value: 12, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.mention': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.code': { '.': { fontFamily: ${MONO}, fontSize: { value: 13, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
    `  'type.code-lang': { '.': { fontFamily: ${SANS}, fontSize: { value: 14, unit: 'px' }, fontWeight: 400, lineHeight: { value: 20, unit: 'px' } } }`,
  ];

  const allEntries = [...colorEntries, ...typeEntries];

  return `// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Shape-compatible with Terrazzo output for backward compat with metrics.ts.
export const tokens = {
${allEntries.join(',\n')},
};
`;
}

function emitTokensDts(): string {
  return `// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Shape-compatible with Terrazzo output.

type ColorChannel = { colorSpace: string; channels: number[]; alpha: number };
type CompositeRole = {
  fontFamily: string[];
  fontSize: { value: number; unit: string };
  fontWeight: number;
  lineHeight: { value: number; unit: string };
  fontStyle?: string;
};

export declare const tokens: {
  [key: string]: { '.': ColorChannel | CompositeRole };
};
`;
}

// ── contract.generated.ts ─────────────────────────────────────────────────────

function emitContractGenerated(): string {
  const slots = Object.keys(SEMANTIC_TEMPLATE);
  const varUnion = slots.map((s) => `'--${s}'`).join('\n  | ');
  return `// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.
// Source of truth: packages/ui/src/theme/contract/semantic-template.ts

/** Union of all semantic CSS custom property names. */
export type SemanticVar =
  | ${varUnion};

/** Array of all semantic CSS custom property names for runtime validation. */
export const SEMANTIC_VARS: readonly SemanticVar[] = [
  ${slots.map((s) => `'--${s}'`).join(',\n  ')},
] as const;
`;
}

// ── theme-manifest.ts ─────────────────────────────────────────────────────────

function emitThemeManifest(themes: ResolvedTheme[]): string {
  const entries = themes.map((t) =>
    `  { id: ${JSON.stringify(t.id)}, label: ${JSON.stringify(t.label)}, polarity: ${JSON.stringify(t.polarity)}, selector: ${JSON.stringify(t.selector)} }`,
  );
  return `// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.

export type ThemeManifestEntry = {
  id: string;
  label: string;
  polarity: 'light' | 'dark';
  selector: string;
};

export const THEME_MANIFEST: readonly ThemeManifestEntry[] = [
${entries.join(',\n')},
] as const;

export type ThemeId = (typeof THEME_MANIFEST)[number]['id'];
`;
}

// ── main ──────────────────────────────────────────────────────────────────────

function run(): void {
  const themes = ALL_THEMES;

  console.log(`Building ${themes.length} theme(s): ${themes.map((t) => t.id).join(', ')}`);

  // theme.css
  const themeCss = emitThemeCss(themes);
  writeFileSync(join(THEME_DIR, 'theme.css'), themeCss, 'utf8');
  console.log('✓ theme.css');

  // semantic.css
  const semanticCss = emitSemanticCss(themes);
  writeFileSync(join(THEME_DIR, 'semantic.css'), semanticCss, 'utf8');
  console.log('✓ semantic.css');

  // tokens.js + tokens.d.ts (use light theme for defaults)
  const defaultForTokens = themes.find((t) => t.polarity === 'light') ?? themes[0];
  writeFileSync(join(THEME_DIR, 'tokens.js'), emitTokensJs(defaultForTokens), 'utf8');
  writeFileSync(join(THEME_DIR, 'tokens.d.ts'), emitTokensDts(), 'utf8');
  console.log('✓ tokens.js + tokens.d.ts');

  // contract.generated.ts
  writeFileSync(
    join(THEME_DIR, 'contract', 'contract.generated.ts'),
    emitContractGenerated(),
    'utf8',
  );
  console.log('✓ contract/contract.generated.ts');

  // Per-theme Shiki JSON files + shiki-themes.ts re-export
  mkdirSync(THEMES_DIR, { recursive: true });
  const shikiExportLines: string[] = [
    '// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.',
    '// Shiki theme objects for multi-theme highlighting.',
    '// Import via @emdash/ui/theme/shiki-themes.',
    '',
  ];
  for (const theme of themes) {
    const shikiPath = join(THEMES_DIR, `${theme.id}.shiki.json`);
    writeFileSync(shikiPath, JSON.stringify(theme.shikiTheme, null, 2), 'utf8');
    console.log(`✓ themes/${theme.id}.shiki.json`);

    shikiExportLines.push(
      `export const ${theme.id}ShikiTheme = ${JSON.stringify(theme.shikiTheme, null, 2)} as const;`,
      '',
    );
  }

  // Named union for theme keys
  const themeIds = themes.map((t) => JSON.stringify(t.id)).join(' | ');
  shikiExportLines.push(`export type ShikiThemeId = ${themeIds};`);
  shikiExportLines.push('');
  shikiExportLines.push(
    `export const ALL_SHIKI_THEMES = [${themes.map((t) => `${t.id}ShikiTheme`).join(', ')}] as const;`,
  );
  shikiExportLines.push('');
  shikiExportLines.push(
    `export const SHIKI_THEME_MAP = { ${themes.map((t) => `${t.id}: ${t.id}ShikiTheme`).join(', ')} } as const;`,
  );

  writeFileSync(join(THEMES_DIR, 'shiki-themes.ts'), shikiExportLines.join('\n'), 'utf8');
  console.log('✓ themes/shiki-themes.ts');

  // theme-manifest.ts
  writeFileSync(join(THEME_DIR, 'theme-manifest.ts'), emitThemeManifest(themes), 'utf8');
  console.log('✓ theme-manifest.ts');

  console.log('\nTheme build complete.');
}

run();
