// Generated by packages/ui/src/theme/build.ts. DO NOT EDIT.

export type ThemeManifestEntry = {
  id: string;
  label: string;
  polarity: 'light' | 'dark';
  selector: string;
};

export const THEME_MANIFEST: readonly ThemeManifestEntry[] = [
  { id: "light", label: "Light", polarity: "light", selector: ".emlight" },
  { id: "dark", label: "Dark", polarity: "dark", selector: ".emdark" },
] as const;

export type ThemeId = (typeof THEME_MANIFEST)[number]['id'];
