/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  'color.neutral.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.988, 0.988, 0.988],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.988, 0.988, 0.988],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.067, 0.067, 0.067],
      alpha: 1,
    },
  },
  'color.neutral.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.975, 0.975, 0.975],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.975, 0.975, 0.975],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.098, 0.098, 0.098],
      alpha: 1,
    },
  },
  'color.neutral.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.135, 0.135, 0.135],
      alpha: 1,
    },
  },
  'color.neutral.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.908, 0.908, 0.908],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.908, 0.908, 0.908],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.163, 0.163, 0.163],
      alpha: 1,
    },
  },
  'color.neutral.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.88, 0.88, 0.88],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.88, 0.88, 0.88],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.192, 0.192, 0.192],
      alpha: 1,
    },
  },
  'color.neutral.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.849, 0.849, 0.849],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.849, 0.849, 0.849],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.228, 0.228, 0.228],
      alpha: 1,
    },
  },
  'color.neutral.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.807, 0.807, 0.807],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.807, 0.807, 0.807],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.283, 0.283, 0.283],
      alpha: 1,
    },
  },
  'color.neutral.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.732, 0.732, 0.732],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.732, 0.732, 0.732],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.375, 0.375, 0.375],
      alpha: 1,
    },
  },
  'color.neutral.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.553, 0.553, 0.553],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.553, 0.553, 0.553],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.431, 0.431, 0.431],
      alpha: 1,
    },
  },
  'color.neutral.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.512, 0.512, 0.512],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.512, 0.512, 0.512],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.484, 0.484, 0.484],
      alpha: 1,
    },
  },
  'color.neutral.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.392, 0.392, 0.392],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.392, 0.392, 0.392],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.706, 0.706, 0.706],
      alpha: 1,
    },
  },
  'color.neutral.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.125, 0.125, 0.125],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.125, 0.125, 0.125],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.933, 0.933, 0.933],
      alpha: 1,
    },
  },
  'color.red.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.998, 0.989, 0.988],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.998, 0.989, 0.988],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.093, 0.068, 0.067],
      alpha: 1,
    },
  },
  'color.red.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.995, 0.971, 0.971],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.995, 0.971, 0.971],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.118, 0.077, 0.079],
      alpha: 1,
    },
  },
  'color.red.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.985, 0.925, 0.925],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.985, 0.925, 0.925],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.211, 0.081, 0.099],
      alpha: 1,
    },
  },
  'color.red.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.999, 0.866, 0.866],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.999, 0.866, 0.866],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.287, 0.079, 0.113],
      alpha: 1,
    },
  },
  'color.red.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.984, 0.812, 0.811],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.984, 0.812, 0.811],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.348, 0.11, 0.142],
      alpha: 1,
    },
  },
  'color.red.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.955, 0.751, 0.749],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.955, 0.751, 0.749],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.414, 0.16, 0.183],
      alpha: 1,
    },
  },
  'color.red.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.915, 0.675, 0.672],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.915, 0.675, 0.672],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.508, 0.224, 0.236],
      alpha: 1,
    },
  },
  'color.red.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.872, 0.575, 0.572],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.872, 0.575, 0.572],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.659, 0.298, 0.297],
      alpha: 1,
    },
  },
  'color.red.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.83, 0.329, 0.324],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.83, 0.329, 0.324],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.83, 0.329, 0.324],
      alpha: 1,
    },
  },
  'color.red.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.798, 0.294, 0.285],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.798, 0.294, 0.285],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.861, 0.403, 0.387],
      alpha: 1,
    },
  },
  'color.red.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.744, 0.234, 0.222],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.744, 0.234, 0.222],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.57, 0.55],
      alpha: 1,
    },
  },
  'color.red.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.36, 0.115, 0.143],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.36, 0.115, 0.143],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.971, 0.826, 0.852],
      alpha: 1,
    },
  },
  'color.green.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.986, 0.996, 0.985],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.986, 0.996, 0.985],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.062, 0.083, 0.067],
      alpha: 1,
    },
  },
  'color.green.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.966, 0.983, 0.964],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.966, 0.983, 0.964],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.083, 0.103, 0.085],
      alpha: 1,
    },
  },
  'color.green.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.923, 0.965, 0.917],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.923, 0.965, 0.917],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.118, 0.163, 0.122],
      alpha: 1,
    },
  },
  'color.green.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.872, 0.94, 0.865],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.872, 0.94, 0.865],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.142, 0.225, 0.15],
      alpha: 1,
    },
  },
  'color.green.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.811, 0.908, 0.802],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.811, 0.908, 0.802],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.178, 0.279, 0.186],
      alpha: 1,
    },
  },
  'color.green.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.733, 0.864, 0.724],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.733, 0.864, 0.724],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.217, 0.337, 0.224],
      alpha: 1,
    },
  },
  'color.green.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.628, 0.803, 0.622],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.628, 0.803, 0.622],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.258, 0.4, 0.264],
      alpha: 1,
    },
  },
  'color.green.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.477, 0.72, 0.482],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.477, 0.72, 0.482],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.302, 0.47, 0.305],
      alpha: 1,
    },
  },
  'color.green.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.38, 0.647, 0.378],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.38, 0.647, 0.378],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.38, 0.647, 0.378],
      alpha: 1,
    },
  },
  'color.green.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.344, 0.598, 0.342],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.344, 0.598, 0.342],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.426, 0.694, 0.426],
      alpha: 1,
    },
  },
  'color.green.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.263, 0.488, 0.261],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.263, 0.488, 0.261],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.535, 0.807, 0.542],
      alpha: 1,
    },
  },
  'color.green.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.151, 0.233, 0.153],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.151, 0.233, 0.153],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.797, 0.936, 0.776],
      alpha: 1,
    },
  },
  'color.blue.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.986, 0.992, 0.999],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.986, 0.992, 0.999],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.057, 0.081, 0.122],
      alpha: 1,
    },
  },
  'color.blue.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.96, 0.979, 0.998],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.96, 0.979, 0.998],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.072, 0.098, 0.147],
      alpha: 1,
    },
  },
  'color.blue.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.912, 0.956, 0.991],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.912, 0.956, 0.991],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.078, 0.154, 0.27],
      alpha: 1,
    },
  },
  'color.blue.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.853, 0.932, 1],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.853, 0.932, 1],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.033, 0.197, 0.37],
      alpha: 1,
    },
  },
  'color.blue.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.788, 0.894, 0.998],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.788, 0.894, 0.998],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.08, 0.245, 0.441],
      alpha: 1,
    },
  },
  'color.blue.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.709, 0.843, 0.976],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.709, 0.843, 0.976],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.14, 0.298, 0.511],
      alpha: 1,
    },
  },
  'color.blue.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.606, 0.777, 0.947],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.606, 0.777, 0.947],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.195, 0.361, 0.6],
      alpha: 1,
    },
  },
  'color.blue.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.451, 0.688, 0.917],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.451, 0.688, 0.917],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.239, 0.434, 0.72],
      alpha: 1,
    },
  },
  'color.blue.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.247, 0.556, 0.969],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.247, 0.556, 0.969],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.247, 0.556, 0.969],
      alpha: 1,
    },
  },
  'color.blue.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.234, 0.523, 0.912],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.234, 0.523, 0.912],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.344, 0.612, 0.973],
      alpha: 1,
    },
  },
  'color.blue.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.15, 0.44, 0.84],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.15, 0.44, 0.84],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.49, 0.72, 1],
      alpha: 1,
    },
  },
  'color.blue.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.102, 0.193, 0.379],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.102, 0.193, 0.379],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.788, 0.898, 0.99],
      alpha: 1,
    },
  },
  'color.yellow.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.992, 0.992, 0.978],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.992, 0.992, 0.978],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.078, 0.069, 0.047],
      alpha: 1,
    },
  },
  'color.yellow.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.995, 0.99, 0.922],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.995, 0.99, 0.922],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.103, 0.094, 0.063],
      alpha: 1,
    },
  },
  'color.yellow.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.997, 0.982, 0.749],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.997, 0.982, 0.749],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.168, 0.137, 0.039],
      alpha: 1,
    },
  },
  'color.yellow.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.992, 0.953, 0.627],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.992, 0.953, 0.627],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.209, 0.169, 0],
      alpha: 1,
    },
  },
  'color.yellow.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.984, 0.91, 0.51],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.984, 0.91, 0.51],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.255, 0.209, 0],
      alpha: 1,
    },
  },
  'color.yellow.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.934, 0.847, 0.474],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.934, 0.847, 0.474],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.31, 0.261, 0.07],
      alpha: 1,
    },
  },
  'color.yellow.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.876, 0.785, 0.46],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.876, 0.785, 0.46],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.389, 0.331, 0.135],
      alpha: 1,
    },
  },
  'color.yellow.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.811, 0.689, 0.313],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.811, 0.689, 0.313],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.497, 0.42, 0.182],
      alpha: 1,
    },
  },
  'color.yellow.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [1, 0.92, 0.22],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [1, 0.92, 0.22],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.92, 0.22],
      alpha: 1,
    },
  },
  'color.yellow.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.977, 0.868, 0.291],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.977, 0.868, 0.291],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 1, 0.456],
      alpha: 1,
    },
  },
  'color.yellow.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.6, 0.44, 0],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.6, 0.44, 0],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.948, 0.885, 0.392],
      alpha: 1,
    },
  },
  'color.yellow.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.271, 0.233, 0.137],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.271, 0.233, 0.137],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.959, 0.934, 0.731],
      alpha: 1,
    },
  },
  'color.purple.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.995, 0.988, 0.996],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.995, 0.988, 0.996],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.09, 0.068, 0.103],
      alpha: 1,
    },
  },
  'color.purple.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.983, 0.971, 0.993],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.983, 0.971, 0.993],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.113, 0.082, 0.134],
      alpha: 1,
    },
  },
  'color.purple.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.963, 0.931, 0.989],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.963, 0.931, 0.989],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.175, 0.112, 0.224],
      alpha: 1,
    },
  },
  'color.purple.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.937, 0.888, 0.981],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.937, 0.888, 0.981],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.224, 0.137, 0.297],
      alpha: 1,
    },
  },
  'color.purple.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.904, 0.837, 0.966],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.904, 0.837, 0.966],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.264, 0.167, 0.349],
      alpha: 1,
    },
  },
  'color.purple.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.86, 0.774, 0.942],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.86, 0.774, 0.942],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.311, 0.208, 0.406],
      alpha: 1,
    },
  },
  'color.purple.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.799, 0.69, 0.91],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.799, 0.69, 0.91],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.381, 0.266, 0.496],
      alpha: 1,
    },
  },
  'color.purple.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.719, 0.583, 0.874],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.719, 0.583, 0.874],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.49, 0.349, 0.649],
      alpha: 1,
    },
  },
  'color.purple.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.523, 0.318, 0.751],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.523, 0.318, 0.751],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.523, 0.318, 0.751],
      alpha: 1,
    },
  },
  'color.purple.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.483, 0.289, 0.7],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.483, 0.289, 0.7],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.57, 0.373, 0.791],
      alpha: 1,
    },
  },
  'color.purple.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.473, 0.281, 0.687],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.473, 0.281, 0.687],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.8, 0.62, 1],
      alpha: 1,
    },
  },
  'color.purple.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.234, 0.132, 0.363],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.234, 0.132, 0.363],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.913, 0.854, 0.971],
      alpha: 1,
    },
  },
  'color.orange.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.995, 0.988, 0.985],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.995, 0.988, 0.985],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.088, 0.07, 0.057],
      alpha: 1,
    },
  },
  'color.orange.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.994, 0.968, 0.934],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.994, 0.968, 0.934],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.113, 0.089, 0.061],
      alpha: 1,
    },
  },
  'color.orange.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.989, 0.938, 0.85],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.989, 0.938, 0.85],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.189, 0.12, 0.056],
      alpha: 1,
    },
  },
  'color.orange.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [1, 0.874, 0.687],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [1, 0.874, 0.687],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.262, 0.132, 0],
      alpha: 1,
    },
  },
  'color.orange.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [1, 0.821, 0.583],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [1, 0.821, 0.583],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.315, 0.168, 0.016],
      alpha: 1,
    },
  },
  'color.orange.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.975, 0.767, 0.545],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.975, 0.767, 0.545],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.376, 0.219, 0.088],
      alpha: 1,
    },
  },
  'color.orange.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.919, 0.693, 0.486],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.919, 0.693, 0.486],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.465, 0.283, 0.147],
      alpha: 1,
    },
  },
  'color.orange.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.877, 0.597, 0.379],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.877, 0.597, 0.379],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.601, 0.359, 0.201],
      alpha: 1,
    },
  },
  'color.orange.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.9, 0.45, 0.2],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.9, 0.45, 0.2],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.9, 0.45, 0.2],
      alpha: 1,
    },
  },
  'color.orange.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.87, 0.409, 0.164],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.87, 0.409, 0.164],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.98, 0.51, 0.23],
      alpha: 1,
    },
  },
  'color.orange.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.76, 0.34, 0],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.76, 0.34, 0],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.63, 0.38],
      alpha: 1,
    },
  },
  'color.orange.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.323, 0.185, 0.127],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.323, 0.185, 0.127],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.98, 0.883, 0.775],
      alpha: 1,
    },
  },
  'color.cyan.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.982, 0.992, 0.996],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.982, 0.992, 0.996],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.053, 0.085, 0.098],
      alpha: 1,
    },
  },
  'color.cyan.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.955, 0.981, 0.984],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.955, 0.981, 0.984],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.072, 0.105, 0.122],
      alpha: 1,
    },
  },
  'color.cyan.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.888, 0.965, 0.975],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.888, 0.965, 0.975],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.073, 0.168, 0.209],
      alpha: 1,
    },
  },
  'color.cyan.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.821, 0.941, 0.959],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.821, 0.941, 0.959],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.063, 0.216, 0.277],
      alpha: 1,
    },
  },
  'color.cyan.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.751, 0.907, 0.935],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.751, 0.907, 0.935],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.091, 0.267, 0.336],
      alpha: 1,
    },
  },
  'color.cyan.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.671, 0.862, 0.9],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.671, 0.862, 0.9],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.137, 0.324, 0.4],
      alpha: 1,
    },
  },
  'color.cyan.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.564, 0.8, 0.854],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.564, 0.8, 0.854],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.186, 0.398, 0.484],
      alpha: 1,
    },
  },
  'color.cyan.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.388, 0.715, 0.798],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.388, 0.715, 0.798],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.23, 0.496, 0.6],
      alpha: 1,
    },
  },
  'color.cyan.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.282, 0.627, 0.765],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.282, 0.627, 0.765],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.282, 0.627, 0.765],
      alpha: 1,
    },
  },
  'color.cyan.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.264, 0.583, 0.71],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.264, 0.583, 0.71],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.331, 0.675, 0.801],
      alpha: 1,
    },
  },
  'color.cyan.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.08, 0.48, 0.63],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.08, 0.48, 0.63],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.446, 0.79, 0.887],
      alpha: 1,
    },
  },
  'color.cyan.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.108, 0.232, 0.277],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.108, 0.232, 0.277],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.757, 0.919, 0.962],
      alpha: 1,
    },
  },
  'color.amber.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.995, 0.992, 0.985],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.995, 0.992, 0.985],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.082, 0.07, 0.05],
      alpha: 1,
    },
  },
  'color.amber.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.994, 0.986, 0.921],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.994, 0.986, 0.921],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.111, 0.094, 0.064],
      alpha: 1,
    },
  },
  'color.amber.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.994, 0.969, 0.782],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.994, 0.969, 0.782],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.178, 0.128, 0.049],
      alpha: 1,
    },
  },
  'color.amber.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.989, 0.937, 0.65],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.989, 0.937, 0.65],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.239, 0.156, 0],
      alpha: 1,
    },
  },
  'color.amber.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.97, 0.902, 0.527],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.97, 0.902, 0.527],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.29, 0.193, 0],
      alpha: 1,
    },
  },
  'color.amber.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.936, 0.844, 0.506],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.936, 0.844, 0.506],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.344, 0.245, 0.076],
      alpha: 1,
    },
  },
  'color.amber.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.89, 0.762, 0.443],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.89, 0.762, 0.443],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.422, 0.314, 0.141],
      alpha: 1,
    },
  },
  'color.amber.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.85, 0.65, 0.3],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.85, 0.65, 0.3],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.535, 0.399, 0.189],
      alpha: 1,
    },
  },
  'color.amber.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [1, 0.77, 0.26],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [1, 0.77, 0.26],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.77, 0.26],
      alpha: 1,
    },
  },
  'color.amber.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.959, 0.741, 0.274],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.959, 0.741, 0.274],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.87, 0.15],
      alpha: 1,
    },
  },
  'color.amber.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.64, 0.4, 0],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.64, 0.4, 0],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [1, 0.8, 0.29],
      alpha: 1,
    },
  },
  'color.amber.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.294, 0.208, 0.145],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.294, 0.208, 0.145],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.984, 0.909, 0.726],
      alpha: 1,
    },
  },
  'color.violet.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.991, 0.988, 0.995],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.991, 0.988, 0.995],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.077, 0.071, 0.118],
      alpha: 1,
    },
  },
  'color.violet.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.978, 0.974, 0.998],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.978, 0.974, 0.998],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.101, 0.084, 0.141],
      alpha: 1,
    },
  },
  'color.violet.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.953, 0.943, 0.993],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.953, 0.943, 0.993],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.154, 0.123, 0.256],
      alpha: 1,
    },
  },
  'color.violet.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.916, 0.897, 1],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.916, 0.897, 1],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.191, 0.148, 0.345],
      alpha: 1,
    },
  },
  'color.violet.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.876, 0.851, 1],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.876, 0.851, 1],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.226, 0.182, 0.396],
      alpha: 1,
    },
  },
  'color.violet.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.825, 0.793, 0.981],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.825, 0.793, 0.981],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.269, 0.223, 0.449],
      alpha: 1,
    },
  },
  'color.violet.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.752, 0.712, 0.943],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.752, 0.712, 0.943],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.326, 0.277, 0.53],
      alpha: 1,
    },
  },
  'color.violet.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.654, 0.602, 0.902],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.654, 0.602, 0.902],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.399, 0.346, 0.656],
      alpha: 1,
    },
  },
  'color.violet.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.417, 0.341, 0.784],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.417, 0.341, 0.784],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.417, 0.341, 0.784],
      alpha: 1,
    },
  },
  'color.violet.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.381, 0.306, 0.741],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.381, 0.306, 0.741],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.477, 0.402, 0.823],
      alpha: 1,
    },
  },
  'color.violet.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.383, 0.317, 0.702],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.383, 0.317, 0.702],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.72, 0.65, 1],
      alpha: 1,
    },
  },
  'color.violet.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.179, 0.15, 0.359],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.179, 0.15, 0.359],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.883, 0.867, 0.986],
      alpha: 1,
    },
  },
  'color.jade.1': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.986, 0.996, 0.992],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.986, 0.996, 0.992],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.059, 0.083, 0.071],
      alpha: 1,
    },
  },
  'color.jade.2': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.962, 0.983, 0.969],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.962, 0.983, 0.969],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.078, 0.11, 0.094],
      alpha: 1,
    },
  },
  'color.jade.3': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.912, 0.965, 0.932],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.912, 0.965, 0.932],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.091, 0.176, 0.138],
      alpha: 1,
    },
  },
  'color.jade.4': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.858, 0.941, 0.893],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.858, 0.941, 0.893],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.102, 0.228, 0.177],
      alpha: 1,
    },
  },
  'color.jade.5': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.795, 0.909, 0.847],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.795, 0.909, 0.847],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.133, 0.279, 0.221],
      alpha: 1,
    },
  },
  'color.jade.6': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.715, 0.864, 0.791],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.715, 0.864, 0.791],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.174, 0.334, 0.273],
      alpha: 1,
    },
  },
  'color.jade.7': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.603, 0.802, 0.718],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.603, 0.802, 0.718],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.219, 0.402, 0.335],
      alpha: 1,
    },
  },
  'color.jade.8': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.44, 0.72, 0.629],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.44, 0.72, 0.629],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.263, 0.488, 0.411],
      alpha: 1,
    },
  },
  'color.jade.9': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.319, 0.63, 0.521],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.319, 0.63, 0.521],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.319, 0.63, 0.521],
      alpha: 1,
    },
  },
  'color.jade.10': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.299, 0.592, 0.488],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.299, 0.592, 0.488],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.338, 0.68, 0.555],
      alpha: 1,
    },
  },
  'color.jade.11': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.15, 0.5, 0.37],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.15, 0.5, 0.37],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.4, 0.835, 0.656],
      alpha: 1,
    },
  },
  'color.jade.12': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.142, 0.229, 0.194],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.142, 0.229, 0.194],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.734, 0.934, 0.838],
      alpha: 1,
    },
  },
  'color.white': {
    '.': {
      colorSpace: 'srgb',
      channels: [1, 1, 1],
      alpha: 1,
      hex: '#ffffff',
    },
    light: {
      colorSpace: 'srgb',
      channels: [1, 1, 1],
      alpha: 1,
      hex: '#ffffff',
    },
    dark: {
      colorSpace: 'srgb',
      channels: [1, 1, 1],
      alpha: 1,
      hex: '#ffffff',
    },
  },
  'surface.sunken': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.067, 0.067, 0.067],
      alpha: 1,
    },
  },
  'surface.base': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.988, 0.988, 0.988],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.988, 0.988, 0.988],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.085, 0.085, 0.085],
      alpha: 1,
    },
  },
  'surface.raised': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.975, 0.975, 0.975],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.975, 0.975, 0.975],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.11, 0.11, 0.11],
      alpha: 1,
    },
  },
  'surface.overlay': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.939, 0.939, 0.939],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.145, 0.145, 0.145],
      alpha: 1,
    },
  },
  'surface.floating': {
    '.': {
      colorSpace: 'display-p3',
      channels: [1, 1, 1],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [1, 1, 1],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.2, 0.2, 0.2],
      alpha: 1,
    },
  },
  'surface.sunken-hover': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8872, 0.8872, 0.8872],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8872, 0.8872, 0.8872],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1022, 0.1022, 0.1022],
      alpha: 1,
    },
  },
  'surface.sunken-selected': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8359, 0.8359, 0.8359],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8359, 0.8359, 0.8359],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.139, 0.139, 0.139],
      alpha: 1,
    },
  },
  'surface.base-hover': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.9356, 0.9356, 0.9356],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.9356, 0.9356, 0.9356],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1211, 0.1211, 0.1211],
      alpha: 1,
    },
  },
  'surface.base-selected': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8838, 0.8838, 0.8838],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8838, 0.8838, 0.8838],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1587, 0.1587, 0.1587],
      alpha: 1,
    },
  },
  'surface.raised-hover': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.9228, 0.9228, 0.9228],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.9228, 0.9228, 0.9228],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1472, 0.1472, 0.1472],
      alpha: 1,
    },
  },
  'surface.raised-selected': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8711, 0.8711, 0.8711],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8711, 0.8711, 0.8711],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1858, 0.1858, 0.1858],
      alpha: 1,
    },
  },
  'surface.overlay-hover': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8872, 0.8872, 0.8872],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8872, 0.8872, 0.8872],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.1835, 0.1835, 0.1835],
      alpha: 1,
    },
  },
  'surface.overlay-selected': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8359, 0.8359, 0.8359],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8359, 0.8359, 0.8359],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.2233, 0.2233, 0.2233],
      alpha: 1,
    },
  },
  'surface.floating-hover': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.9475, 0.9475, 0.9475],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.9475, 0.9475, 0.9475],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.2403, 0.2403, 0.2403],
      alpha: 1,
    },
  },
  'surface.floating-selected': {
    '.': {
      colorSpace: 'display-p3',
      channels: [0.8956, 0.8956, 0.8956],
      alpha: 1,
    },
    light: {
      colorSpace: 'display-p3',
      channels: [0.8956, 0.8956, 0.8956],
      alpha: 1,
    },
    dark: {
      colorSpace: 'display-p3',
      channels: [0.2818, 0.2818, 0.2818],
      alpha: 1,
    },
  },
  'typography.font-family.sans': {
    '.': ['Inter Variable', 'sans-serif'],
  },
  'typography.font-family.mono': {
    '.': ['Cascadia Code', 'ui-monospace', 'monospace'],
  },
  'typography.body.size': {
    '.': {
      value: 14,
      unit: 'px',
    },
  },
  'typography.body.weight': {
    '.': 400,
  },
  'typography.body.line-height': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'typography.body.bold-weight': {
    '.': 700,
  },
  'typography.body.link-weight': {
    '.': 500,
  },
  'typography.h1.size': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'typography.h1.weight': {
    '.': 700,
  },
  'typography.h1.line-height': {
    '.': {
      value: 28,
      unit: 'px',
    },
  },
  'typography.h2.size': {
    '.': {
      value: 17,
      unit: 'px',
    },
  },
  'typography.h2.weight': {
    '.': 700,
  },
  'typography.h2.line-height': {
    '.': {
      value: 25,
      unit: 'px',
    },
  },
  'typography.h3.size': {
    '.': {
      value: 14,
      unit: 'px',
    },
  },
  'typography.h3.weight': {
    '.': 600,
  },
  'typography.h3.line-height': {
    '.': {
      value: 22,
      unit: 'px',
    },
  },
  'typography.code.size': {
    '.': {
      value: 14,
      unit: 'px',
    },
  },
  'typography.code.weight': {
    '.': 400,
  },
  'typography.code.line-height': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'typography.code-lang.size': {
    '.': {
      value: 14,
      unit: 'px',
    },
  },
  'typography.code-lang.weight': {
    '.': 500,
  },
  'typography.code-lang.line-height': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'typography.inline-code.size': {
    '.': {
      value: 12,
      unit: 'px',
    },
  },
  'typography.inline-code.weight': {
    '.': 600,
  },
  'typography.inline-code.line-height': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'typography.mention.size': {
    '.': {
      value: 14,
      unit: 'px',
    },
  },
  'typography.mention.weight': {
    '.': 700,
  },
  'typography.mention.line-height': {
    '.': {
      value: 20,
      unit: 'px',
    },
  },
  'type.body': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 400,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.body-bold': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 700,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.body-italic': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 400,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
      fontStyle: 'italic',
    },
  },
  'type.body-link': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 500,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.h1': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 20,
        unit: 'px',
      },
      fontWeight: 700,
      lineHeight: {
        value: 28,
        unit: 'px',
      },
    },
  },
  'type.h2': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 17,
        unit: 'px',
      },
      fontWeight: 700,
      lineHeight: {
        value: 25,
        unit: 'px',
      },
    },
  },
  'type.h3': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 600,
      lineHeight: {
        value: 22,
        unit: 'px',
      },
    },
  },
  'type.inline-code': {
    '.': {
      fontFamily: ['Cascadia Code', 'ui-monospace', 'monospace'],
      fontSize: {
        value: 12,
        unit: 'px',
      },
      fontWeight: 600,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.mention': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 700,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.code': {
    '.': {
      fontFamily: ['Cascadia Code', 'ui-monospace', 'monospace'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 400,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'type.code-lang': {
    '.': {
      fontFamily: ['Inter Variable', 'sans-serif'],
      fontSize: {
        value: 14,
        unit: 'px',
      },
      fontWeight: 500,
      lineHeight: {
        value: 20,
        unit: 'px',
      },
    },
  },
  'radius.sm': {
    '.': {
      value: 4,
      unit: 'px',
    },
  },
  'radius.md': {
    '.': {
      value: 6,
      unit: 'px',
    },
  },
  'radius.base': {
    '.': {
      value: 8,
      unit: 'px',
    },
  },
  'radius.lg': {
    '.': {
      value: 12,
      unit: 'px',
    },
  },
  'radius.full': {
    '.': {
      value: 9999,
      unit: 'px',
    },
  },
  'fade.size': {
    '.': {
      value: 24,
      unit: 'px',
    },
  },
  'fade.softness': {
    '.': 0.4,
  },
};

/** Get individual token */
export function token(tokenID, modeName = '.') {
  return tokens[tokenID]?.[modeName];
}
