/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type {
  ColorTokenNormalized,
  DimensionTokenNormalized,
  FontFamilyTokenNormalized,
  FontWeightTokenNormalized,
  NumberTokenNormalized,
  TypographyTokenNormalized,
} from '@terrazzo/parser';

export declare const tokens: {
  'color.neutral.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.neutral.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.red.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.green.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.blue.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.yellow.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.purple.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.orange.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.cyan.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.amber.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.violet.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.3': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.4': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.5': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.6': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.7': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.8': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.9': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.10': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.11': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.jade.12': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'color.white': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.sunken': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.base': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.raised': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.overlay': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.floating': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.sunken-hover': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.sunken-selected': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.base-hover': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.base-selected': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.raised-hover': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.raised-selected': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.overlay-hover': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.overlay-selected': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.floating-hover': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'surface.floating-selected': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'typography.font-family.sans': Record<'.', FontFamilyTokenNormalized['$value']>;
  'typography.font-family.mono': Record<'.', FontFamilyTokenNormalized['$value']>;
  'typography.body.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.body.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.body.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.body.bold-weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.body.link-weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.h1.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.h1.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.h1.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.h2.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.h2.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.h2.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.h3.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.h3.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.h3.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.code.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.code.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.code.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.code-lang.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.code-lang.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.code-lang.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.inline-code.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.inline-code.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.inline-code.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.mention.size': Record<'.', DimensionTokenNormalized['$value']>;
  'typography.mention.weight': Record<'.', FontWeightTokenNormalized['$value']>;
  'typography.mention.line-height': Record<'.', DimensionTokenNormalized['$value']>;
  'type.body': Record<'.', TypographyTokenNormalized['$value']>;
  'type.body-bold': Record<'.', TypographyTokenNormalized['$value']>;
  'type.body-italic': Record<'.', TypographyTokenNormalized['$value']>;
  'type.body-link': Record<'.', TypographyTokenNormalized['$value']>;
  'type.h1': Record<'.', TypographyTokenNormalized['$value']>;
  'type.h2': Record<'.', TypographyTokenNormalized['$value']>;
  'type.h3': Record<'.', TypographyTokenNormalized['$value']>;
  'type.inline-code': Record<'.', TypographyTokenNormalized['$value']>;
  'type.mention': Record<'.', TypographyTokenNormalized['$value']>;
  'type.code': Record<'.', TypographyTokenNormalized['$value']>;
  'type.code-lang': Record<'.', TypographyTokenNormalized['$value']>;
  'radius.sm': Record<'.', DimensionTokenNormalized['$value']>;
  'radius.md': Record<'.', DimensionTokenNormalized['$value']>;
  'radius.base': Record<'.', DimensionTokenNormalized['$value']>;
  'radius.lg': Record<'.', DimensionTokenNormalized['$value']>;
  'radius.full': Record<'.', DimensionTokenNormalized['$value']>;
  'fade.size': Record<'.', DimensionTokenNormalized['$value']>;
  'fade.softness': Record<'.', NumberTokenNormalized['$value']>;
  'semantic.background': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.background-1': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-2': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-3': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-inverse': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  /** Rendered as color-mix(in srgb, var(--neutral-11) 40%, var(--neutral-12)); see terrazzo.config.js transform() */
  'semantic.foreground-body': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-muted': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-passive': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.background-destructive': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.background-destructive-1': Record<
    '.' | 'light' | 'dark',
    ColorTokenNormalized['$value']
  >;
  'semantic.foreground-destructive': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.foreground-destructive-muted': Record<
    '.' | 'light' | 'dark',
    ColorTokenNormalized['$value']
  >;
  'semantic.background-neutral': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-neutral': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.primary-button-background': Record<
    '.' | 'light' | 'dark',
    ColorTokenNormalized['$value']
  >;
  'semantic.primary-button-background-hover': Record<
    '.' | 'light' | 'dark',
    ColorTokenNormalized['$value']
  >;
  'semantic.primary-button-foreground': Record<
    '.' | 'light' | 'dark',
    ColorTokenNormalized['$value']
  >;
  /** Light mode is transparent; see terrazzo.config.js transform() */
  'semantic.primary-button-border': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.border': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.border-1': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.border-2': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.border-destructive': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.border-primary': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.selection': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.selection-foreground': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.status-in-progress': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.status-in-review': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.status-done': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.status-todo': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.status-cancelled': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.foreground-diff-added': Record<'.' | 'light' | 'dark', ColorTokenNormalized['$value']>;
  'semantic.foreground-diff-modified': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-diff-deleted': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-success': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-success': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-success-hover': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.border-success': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-error': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-error': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-error-hover': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.border-error': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-warning': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-warning': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-warning-hover': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.border-warning': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-info': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-info': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.background-info-hover': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.border-info': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-conflict': Record<'.', ColorTokenNormalized['$value']>;
  'semantic.foreground-merged': Record<'.', ColorTokenNormalized['$value']>;
};

export declare function token<K extends keyof typeof tokens>(
  tokenID: K,
  modeName?: never
): (typeof tokens)[K]['.'];
export declare function token<K extends keyof typeof tokens, M extends keyof (typeof tokens)[K]>(
  tokenID: K,
  modeName: M
): (typeof tokens)[K][M];
