/**
 * codegen/emit-theme-css.ts
 *
 * Emits styles/theme.css — the full palette + per-theme semantic var blocks.
 * :root contains all vars from the light theme as defaults; each .em<id>
 * block overrides all vars for that theme.
 */

import type { ResolvedTheme } from '../define-theme';

export function emitThemeCss(themes: ResolvedTheme[]): string {
  const lines: string[] = [
    '/* -------------------------------------------',
    ' *  Generated by packages/ui/src/theme/core/codegen/run.ts',
    ' *  DO NOT EDIT — run pnpm theme:build to regenerate.',
    ' * ------------------------------------------- */',
    '',
  ];

  // :root — default vars using the light theme as fallback
  const defaultTheme = themes.find((t) => t.polarity === 'light') ?? themes[0];
  lines.push(':root {');
  for (const [prop, value] of Object.entries(defaultTheme.cssVars)) {
    lines.push(`  ${prop}: ${value};`);
  }
  lines.push('}', '');

  // Per-theme selectors
  for (const theme of themes) {
    lines.push(`${theme.selector} {`);
    for (const [prop, value] of Object.entries(theme.cssVars)) {
      lines.push(`  ${prop}: ${value};`);
    }
    lines.push('}', '');
  }

  return lines.join('\n');
}
