export { INSTALL_METHOD_LOCATION_HINTS, inferMethod } from './location-hints';
export { resolveInstallOptions, pickInstallOption, toPlatform } from './install-options';
export {
  deriveHostDependencyStatus,
  hostDependencySelectionSchema,
  installationCanUpdate,
  type DependencyCategory,
  type DependencyDescriptor,
  type DependencyId,
  type DependencyInstallError,
  type DependencyInstallResult,
  type DependencyProbeOptions,
  type DependencyState,
  type DependencyStatus,
  type DependencyStatusMap,
  type DependencyStatusUpdatedEvent,
  type DependencyUninstallError,
  type DependencyUninstallResult,
  type DependencyUpdateError,
  type DependencyUpdateResult,
  type HostDependency,
  type HostDependencySelection,
  type InstallCommandError,
  type Installation,
  type InstallationSource,
  type ProbeResult,
} from './types';
